<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */

namespace Tablas\Model\Entity;
interface CatpuestoInterface{
    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */            
   public function setId($id);
    /**
     * Get id
     *
     * @return int
     */          
   public function getId();
    /**
     * Set nombre
     *
     * @param varchar $nombre
     * @return type                   
     */            
   public function setNombre($nombre);
    /**
     * Get nombre
     *
     * @return varchar
     */          
   public function getNombre();
}
?>