<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */

namespace Tablas\Model\Entity;
class Fuerzaventamen implements FuerzaventamenInterface{
    /**
     * @var int              
     */
      protected $id;  
    /**
     * @var tinyint              
     */
      protected $unidadnegocio;  
    /**
     * @var tinyint              
     */
      protected $canal;  
    /**
     * @var tinyint              
     */
      protected $zonaregion;  
    /**
     * @var varchar              
     */
      protected $division;  
    /**
     * @var varchar              
     */
      protected $agencia;  
    /**
     * @var varchar              
     */
      protected $appaterno;  
    /**
     * @var varchar              
     */
      protected $apmaterno;  
    /**
     * @var varchar              
     */
      protected $nombres;  
    /**
     * @var int              
     */
      protected $puesto;  
    /**
     * @var tinyint              
     */
      protected $contrato;  
    /**
     * @var int              
     */
      protected $nomina;  
    /**
     * @var date              
     */
      protected $fechanacim;  
    /**
     * @var enum              
     */
      protected $sexo;  
    /**
     * @var tinyint              
     */
      protected $idq;  
    /**
     * @var varchar              
     */
      protected $qcorresp;  
    /**
     * @var tinyint              
     */
      protected $idcatalogo;  
    /**
     * @var int              
     */
      protected $idusername;  
    /**
     * @var int              
     */
      protected $fecha;  
    /**
     * @var tinyint              
     */
      protected $estado;  
    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */            
	public function setId($id){
		$this->id = (int) $id;
	}
    /**
     * Get id
     *
     * @return int
     */          
	public function getId(){
		return $this->id;
	}
    /**
     * Set unidadnegocio
     *
     * @param tinyint $unidadnegocio
     * @return type                   
     */            
	public function setUnidadnegocio($unidadnegocio){
		$this->unidadnegocio = (int) $unidadnegocio;
	}
    /**
     * Get unidadnegocio
     *
     * @return tinyint
     */          
	public function getUnidadnegocio(){
		return $this->unidadnegocio;
	}
    /**
     * Set canal
     *
     * @param tinyint $canal
     * @return type                   
     */            
	public function setCanal($canal){
		$this->canal = (int) $canal;
	}
    /**
     * Get canal
     *
     * @return tinyint
     */          
	public function getCanal(){
		return $this->canal;
	}
    /**
     * Set zonaregion
     *
     * @param tinyint $zonaregion
     * @return type                   
     */            
	public function setZonaregion($zonaregion){
		$this->zonaregion = (int) $zonaregion;
	}
    /**
     * Get zonaregion
     *
     * @return tinyint
     */          
	public function getZonaregion(){
		return $this->zonaregion;
	}
    /**
     * Set division
     *
     * @param varchar $division
     * @return type                   
     */            
	public function setDivision($division){
		$this->division = (string) $division;
	}
    /**
     * Get division
     *
     * @return varchar
     */          
	public function getDivision(){
		return $this->division;
	}
    /**
     * Set agencia
     *
     * @param varchar $agencia
     * @return type                   
     */            
	public function setAgencia($agencia){
		$this->agencia = (string) $agencia;
	}
    /**
     * Get agencia
     *
     * @return varchar
     */          
	public function getAgencia(){
		return $this->agencia;
	}
    /**
     * Set appaterno
     *
     * @param varchar $appaterno
     * @return type                   
     */            
	public function setAppaterno($appaterno){
		$this->appaterno = (string) $appaterno;
	}
    /**
     * Get appaterno
     *
     * @return varchar
     */          
	public function getAppaterno(){
		return $this->appaterno;
	}
    /**
     * Set apmaterno
     *
     * @param varchar $apmaterno
     * @return type                   
     */            
	public function setApmaterno($apmaterno){
		$this->apmaterno = (string) $apmaterno;
	}
    /**
     * Get apmaterno
     *
     * @return varchar
     */          
	public function getApmaterno(){
		return $this->apmaterno;
	}
    /**
     * Set nombres
     *
     * @param varchar $nombres
     * @return type                   
     */            
	public function setNombres($nombres){
		$this->nombres = (string) $nombres;
	}
    /**
     * Get nombres
     *
     * @return varchar
     */          
	public function getNombres(){
		return $this->nombres;
	}
    /**
     * Set puesto
     *
     * @param int $puesto
     * @return type                   
     */            
	public function setPuesto($puesto){
		$this->puesto = (int) $puesto;
	}
    /**
     * Get puesto
     *
     * @return int
     */          
	public function getPuesto(){
		return $this->puesto;
	}
    /**
     * Set contrato
     *
     * @param tinyint $contrato
     * @return type                   
     */            
	public function setContrato($contrato){
		$this->contrato = (int) $contrato;
	}
    /**
     * Get contrato
     *
     * @return tinyint
     */          
	public function getContrato(){
		return $this->contrato;
	}
    /**
     * Set nomina
     *
     * @param int $nomina
     * @return type                   
     */            
	public function setNomina($nomina){
		$this->nomina = (int) $nomina;
	}
    /**
     * Get nomina
     *
     * @return int
     */          
	public function getNomina(){
		return $this->nomina;
	}
    /**
     * Set fechanacim
     *
     * @param date $fechanacim
     * @return type                   
     */            
	public function setFechanacim($fechanacim){
		$this->fechanacim = (string) $fechanacim;
	}
    /**
     * Get fechanacim
     *
     * @return date
     */          
	public function getFechanacim(){
		return $this->fechanacim;
	}
    /**
     * Set sexo
     *
     * @param enum $sexo
     * @return type                   
     */            
	public function setSexo($sexo){
		$this->sexo = (string) $sexo;
	}
    /**
     * Get sexo
     *
     * @return enum
     */          
	public function getSexo(){
		return $this->sexo;
	}
    /**
     * Set idq
     *
     * @param tinyint $idq
     * @return type                   
     */            
	public function setIdq($idq){
		$this->idq = (int) $idq;
	}
    /**
     * Get idq
     *
     * @return tinyint
     */          
	public function getIdq(){
		return $this->idq;
	}
    /**
     * Set qcorresp
     *
     * @param varchar $qcorresp
     * @return type                   
     */            
	public function setQcorresp($qcorresp){
		$this->qcorresp = (string) $qcorresp;
	}
    /**
     * Get qcorresp
     *
     * @return varchar
     */          
	public function getQcorresp(){
		return $this->qcorresp;
	}
    /**
     * Set idcatalogo
     *
     * @param tinyint $idcatalogo
     * @return type                   
     */            
	public function setIdcatalogo($idcatalogo){
		$this->idcatalogo = (int) $idcatalogo;
	}
    /**
     * Get idcatalogo
     *
     * @return tinyint
     */          
	public function getIdcatalogo(){
		return $this->idcatalogo;
	}
    /**
     * Set idusername
     *
     * @param int $idusername
     * @return type                   
     */            
	public function setIdusername($idusername){
		$this->idusername = (int) $idusername;
	}
    /**
     * Get idusername
     *
     * @return int
     */          
	public function getIdusername(){
		return $this->idusername;
	}
    /**
     * Set fecha
     *
     * @param int $fecha
     * @return type                   
     */            
	public function setFecha($fecha){
		$this->fecha = (int) $fecha;
	}
    /**
     * Get fecha
     *
     * @return int
     */          
	public function getFecha(){
		return $this->fecha;
	}
    /**
     * Set estado
     *
     * @param tinyint $estado
     * @return type                   
     */            
	public function setEstado($estado){
		$this->estado = (int) $estado;
	}
    /**
     * Get estado
     *
     * @return tinyint
     */          
	public function getEstado(){
		return $this->estado;
	}
}
?>