<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */

namespace Tablas\Model\Entity;
interface FuerzaventamenInterface{
    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */            
   public function setId($id);
    /**
     * Get id
     *
     * @return int
     */          
   public function getId();
    /**
     * Set unidadnegocio
     *
     * @param tinyint $unidadnegocio
     * @return type                   
     */            
   public function setUnidadnegocio($unidadnegocio);
    /**
     * Get unidadnegocio
     *
     * @return tinyint
     */          
   public function getUnidadnegocio();
    /**
     * Set canal
     *
     * @param tinyint $canal
     * @return type                   
     */            
   public function setCanal($canal);
    /**
     * Get canal
     *
     * @return tinyint
     */          
   public function getCanal();
    /**
     * Set zonaregion
     *
     * @param tinyint $zonaregion
     * @return type                   
     */            
   public function setZonaregion($zonaregion);
    /**
     * Get zonaregion
     *
     * @return tinyint
     */          
   public function getZonaregion();
    /**
     * Set division
     *
     * @param varchar $division
     * @return type                   
     */            
   public function setDivision($division);
    /**
     * Get division
     *
     * @return varchar
     */          
   public function getDivision();
    /**
     * Set agencia
     *
     * @param varchar $agencia
     * @return type                   
     */            
   public function setAgencia($agencia);
    /**
     * Get agencia
     *
     * @return varchar
     */          
   public function getAgencia();
    /**
     * Set appaterno
     *
     * @param varchar $appaterno
     * @return type                   
     */            
   public function setAppaterno($appaterno);
    /**
     * Get appaterno
     *
     * @return varchar
     */          
   public function getAppaterno();
    /**
     * Set apmaterno
     *
     * @param varchar $apmaterno
     * @return type                   
     */            
   public function setApmaterno($apmaterno);
    /**
     * Get apmaterno
     *
     * @return varchar
     */          
   public function getApmaterno();
    /**
     * Set nombres
     *
     * @param varchar $nombres
     * @return type                   
     */            
   public function setNombres($nombres);
    /**
     * Get nombres
     *
     * @return varchar
     */          
   public function getNombres();
    /**
     * Set puesto
     *
     * @param int $puesto
     * @return type                   
     */            
   public function setPuesto($puesto);
    /**
     * Get puesto
     *
     * @return int
     */          
   public function getPuesto();
    /**
     * Set contrato
     *
     * @param tinyint $contrato
     * @return type                   
     */            
   public function setContrato($contrato);
    /**
     * Get contrato
     *
     * @return tinyint
     */          
   public function getContrato();
    /**
     * Set nomina
     *
     * @param int $nomina
     * @return type                   
     */            
   public function setNomina($nomina);
    /**
     * Get nomina
     *
     * @return int
     */          
   public function getNomina();
    /**
     * Set fechanacim
     *
     * @param date $fechanacim
     * @return type                   
     */            
   public function setFechanacim($fechanacim);
    /**
     * Get fechanacim
     *
     * @return date
     */          
   public function getFechanacim();
    /**
     * Set sexo
     *
     * @param enum $sexo
     * @return type                   
     */            
   public function setSexo($sexo);
    /**
     * Get sexo
     *
     * @return enum
     */          
   public function getSexo();
    /**
     * Set idq
     *
     * @param tinyint $idq
     * @return type                   
     */            
   public function setIdq($idq);
    /**
     * Get idq
     *
     * @return tinyint
     */          
   public function getIdq();
    /**
     * Set qcorresp
     *
     * @param varchar $qcorresp
     * @return type                   
     */            
   public function setQcorresp($qcorresp);
    /**
     * Get qcorresp
     *
     * @return varchar
     */          
   public function getQcorresp();
    /**
     * Set idcatalogo
     *
     * @param tinyint $idcatalogo
     * @return type                   
     */            
   public function setIdcatalogo($idcatalogo);
    /**
     * Get idcatalogo
     *
     * @return tinyint
     */          
   public function getIdcatalogo();
    /**
     * Set idusername
     *
     * @param int $idusername
     * @return type                   
     */            
   public function setIdusername($idusername);
    /**
     * Get idusername
     *
     * @return int
     */          
   public function getIdusername();
    /**
     * Set fecha
     *
     * @param int $fecha
     * @return type                   
     */            
   public function setFecha($fecha);
    /**
     * Get fecha
     *
     * @return int
     */          
   public function getFecha();
    /**
     * Set estado
     *
     * @param tinyint $estado
     * @return type                   
     */            
   public function setEstado($estado);
    /**
     * Get estado
     *
     * @return tinyint
     */          
   public function getEstado();
}
?>